apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: personal-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 449024774815.dkr.ecr.eu-north-1.amazonaws.com/personal-manager-frontend:74d6ebb86558068c8c7aff971e85f8346812c905
          ports:
            - containerPort: 80
