apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eyaoueratni/pesonal-manager
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
