apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: personal-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "homebase"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
